### ISSUE TITLE
Parser in example crashes on ISO-8601 DateTime Strings

### ISSUE THREAD

**Issue by tionis** [olebedev/when#32]
The following string crashes the exampel with a Segmentation Violation:
```
2022-01-15T22:00
```

**Comment by olebedev** [comment]
Hi @tionis, thanks for the report.

The tool it not defined to work with the ISO-8601 data format. I think, you would want to use the `time.Parse` function from the standard Golang library for that operation. 

Also, the string you have provided doesn't follow the convention the the format you're linking to. See the https://datatracker.ietf.org/doc/html/rfc3339#section-5.6, and 
```
date-time       = full-date "T" full-time
```
in particular.

**Comment by olebedev** [comment]
However, having the `when` lib crashed on random input doesn't sound great! I would be happy to review a PR that deals with that crash and make the library just return `nil` instead of crashing.

**Comment by tionis** [comment]
I see.
If I integrate when into my project and maybe fix this problem, I would be happy to upstream it.
